### ISSUE TITLE
Unknown audio/video stream combination

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#19]
Traceback (most recent call last):
  File "/home/daniel/open-access-media-importer/helpers/media.py", line 48, in on_message
    raise RuntimeError, str(err)
RuntimeError: Could not demultiplex stream.
## Unknown audio/video stream combination. Skipping conversion of “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0030940.s002.mov”.

Affected DOI:
10.1371/journal.pone.0030940

**Comment by erlehmann** [comment]
Added to GStreamer bug 686550: https://bugzilla.gnome.org/show_bug.cgi?id=686550

**Comment by Daniel-Mietchen** [comment]
OK, knowing that, we should now just make sure the program does not crash at that point.

**Comment by erlehmann** [comment]
GStreamer claims to have it fixed. https://bugzilla.gnome.org/show_bug.cgi?id=686550

**Comment by Daniel-Mietchen** [comment]
OK, how can we pull their fix in? Just reran that DOI:

daniel@oami-host:~/open-access-media-importer$ echo 10.1371/journal.pone.0030940 | ./oami_pmc_doi_import
Removing “/home/daniel/.local/share/open-access-media-importer/pmc_doi.sqlite” … done.
Input DOIs, delimited by whitespace: Getting PubMed Central IDs for given DOIs … found: 3266281
Downloading “http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=3266281”, saving into directory “/home/daniel/.cache/open-access-media-importer/metadata/raw/pmc_doi” …
100% |#########################################################################|
/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:463: SAWarning: Unicode type received non-unicode bind param value.
  param.append(processors[key](compiled_params[key]))
“High Resolution In Vivo Bioluminescent Imaging for the Study of Bacterial Tumour Targeting”:
    2 × video/quicktime
    1 × video/x-msvideo
    1 × image/tiff

Checking MIME types …
100% |#########################################################################|
Skipping http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3266281/bin/pone.0030940.s001.avi.
Skipping http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3266281/bin/pone.0030940.s002.mov.
Skipping http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3266281/bin/pone.0030940.s003.mov.
Converting “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0030940.s002.mov”, saving into “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0030940.s002.mov.ogv” … Traceback (most recent call last):
  File "/home/daniel/open-access-media-importer/helpers/media.py", line 48, in on_message
    raise RuntimeError, str(err)
RuntimeError: Could not demultiplex stream.
Unknown audio/video stream combination. Skipping conversion of “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0030940.s002.mov”.
Skipping “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0030940.s001.avi.ogv”, already exists at http://commons.wikimedia.org/w/api.php.
Skipping “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0030940.s003.mov.ogv”, already exists at http://commons.wikimedia.org/w/api.php.

**Comment by erlehmann** [comment]
We will have to wait for Debian to upgrade GStreamer – or build it ourself. I would like to avoid the latter, as it is a media framework with lots of dependencies. Re-running the importer at any point in the future is most likely much less work.

**Comment by Daniel-Mietchen** [comment]
Another affected DOI:
10.1371/journal.pbio.0060209 - only some videos, though.

**Comment by Daniel-Mietchen** [comment]
Some more: 
10.1371/journal.pone.0000602
10.1371/journal.pone.0024799
10.1371/journal.pone.0038517
10.1371/journal.pone.0029897
10.1371/journal.pbio.1001059

**Comment by Daniel-Mietchen** [comment]
Another one:
10.1371/journal.pone.0063556

**Comment by Daniel-Mietchen** [comment]
Another one:
10.1371/journal.pone.0077487
