### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#26]
Input DOIs, delimited by whitespace: Getting PubMed Central IDs for given DOIs … found: 
Downloading “http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=”, saving into directory “/home/daniel/.cache/open-access-media-importer/metadata/raw/pmc_doi” …
When trying to download http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=, the following error occured: “HTTP Error 400: Bad Request”.                                                      |
Traceback (most recent call last):
  File "./oa-cache", line 206, in <module>
    skip=skip
  File "/home/daniel/open-access-media-importer/sources/pmc_doi.py", line 71, in list_articles
    result_tree.parse(path.join(target_directory, filename))
  File "<string>", line 38, in parse
cElementTree.ParseError: no element found: line 1, column 0
Traceback (most recent call last):
  File "./oa-get", line 55, in <module>
    p = progressbar.ProgressBar(maxval=len(materials))
  File "/usr/lib/pymodules/python2.7/progressbar.py", line 218, in **init**
    assert maxval > 0
## AssertionError

Affected DOI:
10.1186/1471-2261-2-1

**Comment by erlehmann** [comment]
Probably fixed by 3ad58d7fe80afcbf4d8255e4902a124eff1a1bdd.
