### ISSUE TITLE
ERROR: Ihrer Installation von GStreamer fehlt ein Plugin. 

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#69]
danielmietchen@wiki:~/open-access-media-importer$ echo 10.1371/journal.pone.0059743 | ./oami_pmc_doi_import
Input DOIs, delimited by whitespace: Getting PubMed Central IDs for given DOIs … found: 3609797
Downloading “http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=3609797”, saving into directory “/home/danielmietchen/.cache/open-access-media-importer/metadata/raw/pmc_doi” …
100% |#########################################################################|
/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:463: SAWarning: Unicode type received non-unicode bind param value.
  param.append(processors[key](compiled_params[key]))
“Cunnilingus Apparently Increases Duration of Copulation in the Indian Flying Fox, Pteropus giganteus”:
    1 × video/x-ms-wmv

Checking MIME types …
/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:463: SAWarning: Unicode type received non-unicode bind param value.
  param.append(processors[key](compiled_params[key]))
DOI 10.1371/journal.pone.0059743, http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3609797/bin/pone.0059743.s001.wmv, source claimed video/x-ms-wmv but is video/x-ms-asf.
100% |#########################################################################|
Skipping download of http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3609797/bin/pone.0059743.s001.wmv.
Converting “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0059743.s001.wmv”, saving into “/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0059743.s001.wmv.ogv” … ERROR: Ihrer Installation von GStreamer fehlt ein Plugin.
ERROR:root:Unknown audio/video stream combination.: Skipping conversion of “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0059743.s001.wmv”.

**Comment by RaphaelWimmer** [comment]
I installed the package _gstreamer0.10-plugins-ugly_0.10.19-2+b2_amd64.deb_ which contains support for the Microsoft ASF container format.
This should fix the issue.

**Comment by Daniel-Mietchen** [comment]
Yes, it worked for this one now - thanks!
http://commons.wikimedia.org/wiki/File:Cunnilingus-Apparently-Increases-Duration-of-Copulation-in-the-Indian-Flying-Fox-Pteropus-giganteus-pone.0059743.s001.ogv

**Comment by Daniel-Mietchen** [comment]
Here's another one with this error:

danielmietchen@wiki:~/open-access-media-importer$ ./oa-cache clear-database pmc_doi ; echo 10.1371/journal.pone.0061541 | ./oami_pmc_doi_import 
Removing “/home/danielmietchen/.local/share/open-access-media-importer/pmc_doi.sqlite” … done.
Input DOIs, delimited by whitespace: Getting PubMed Central IDs for given DOIs … found: 3631201
Downloading “http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=3631201”, saving into directory “/home/danielmietchen/.cache/open-access-media-importer/metadata/raw/pmc_doi” …
100% |#########################################################################################################################|
/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:463: SAWarning: Unicode type received non-unicode bind param value.
  param.append(processors[key](compiled_params[key]))
“Dual Action of BPC194: A Membrane Active Peptide Killing Bacterial Cells”:
    5 × video/x-msvideo
    1 × application/msword

Checking MIME types …
100% |#########################################################################################################################|
Skipping download of http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3631201/bin/pone.0061541.s001.avi.
Skipping download of http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3631201/bin/pone.0061541.s002.avi.
Skipping download of http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3631201/bin/pone.0061541.s003.avi.
Skipping download of http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3631201/bin/pone.0061541.s004.avi.
Skipping download of http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3631201/bin/pone.0061541.s005.avi.
Converting “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0061541.s001.avi”, saving into “/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0061541.s001.avi.ogv” … ERROR: Ihrer Installation von GStreamer fehlt ein Plugin.
ERROR:root:Unknown audio/video stream combination.: Skipping conversion of “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0061541.s001.avi”.
Converting “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0061541.s002.avi”, saving into “/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0061541.s002.avi.ogv” … ERROR: Ihrer Installation von GStreamer fehlt ein Plugin.
ERROR:root:Unknown audio/video stream combination.: Skipping conversion of “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0061541.s002.avi”.
Converting “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0061541.s003.avi”, saving into “/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0061541.s003.avi.ogv” … ERROR: Ihrer Installation von GStreamer fehlt ein Plugin.
ERROR:root:Unknown audio/video stream combination.: Skipping conversion of “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0061541.s003.avi”.
Skipping conversion of “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0061541.s004.avi”, exists at “/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0061541.s004.avi.ogv”.
Skipping conversion of “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pone.0061541.s005.avi”, exists at “/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0061541.s005.avi.ogv”.
“/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0061541.s004.avi.ogv” uploaded to http://commons.wikimedia.org/w/api.php.
“/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/pone.0061541.s005.avi.ogv” uploaded to http://commons.wikimedia.org/w/api.php.

**Comment by RaphaelWimmer** [comment]
The files seem to be encoded as a sequence of PNG files. While FFmpeg can decode this, and gstreamer0.10-ffmpeg is installed, gstreamer seems to be unable to recognize the format.
I am not sure what the best way to fix this would be.

**Comment by Daniel-Mietchen** [comment]
Another one:
10.1371/journal.pone.0030293

**Comment by Daniel-Mietchen** [comment]
17 of 19 videos affected in 10.1371/journal.pgen.1001219, e.g.

Converting “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pgen.1001219.s016.mov”, saving into “/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/pgen.1001219.s016.mov.ogv” … ERROR: Ihrer Installation von GStreamer fehlt ein Plugin.
ERROR:root:Unknown audio/video stream combination.: Skipping conversion of “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/pgen.1001219.s016.mov”.

**Comment by erlehmann** [comment]
Further testing:

<pre>desudesudesu ~/src/open-access-media-importer on master(2013.1-29-g1d6b0a3) tracking origin/master exited 1
1007 open-access-media-importer:master? % ./oami-converter-test.py http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3631201/bin/pone.0061541.s001.avi
Getting file from <http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3631201/bin/pone.0061541.s001.avi>, writing to “oami-gstreamer-test-input” … done.
Setting up Media helper for “oami-gstreamer-test-input”… done.
Attempting finding streams of “oami-gstreamer-test-input” … ERROR: Ihrer Installation von GStreamer fehlt ein Plugin.
done.
Attempting conversion of “oami-gstreamer-test-input”, writing into “oami-gstreamer-test-output” … Traceback (most recent call last):
  File "./oami-converter-test.py", line 39, in <module>
    m.convert(output_filename)
  File "/home/erlehmann/src/open-access-media-importer/helpers/media.py", line 88, in convert
    raise RuntimeError, 'Unknown audio/video stream combination.'
RuntimeError: Unknown audio/video stream combination.
</pre>

**Comment by erlehmann** [comment]
Bug filed against GStreamer https://bugzilla.gnome.org/show_bug.cgi?id=704291

**Comment by erlehmann** [comment]
Bug filed against GStreamer https://bugzilla.gnome.org/show_bug.cgi?id=704292

**Comment by erlehmann** [comment]
Bug filed against GStreamer https://bugzilla.gnome.org/show_bug.cgi?id=704294

**Comment by erlehmann** [comment]
Changing label to “Delegated to third party” as the resolution of this kind of bugs depends on GStreamer.

**Comment by erlehmann** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=704291 seems to be solved in GStreamer already.

**Comment by erlehmann** [comment]
Raphael, has the bugfix already made it to the GStreamer packages installed on the OAMI server?

**Comment by RaphaelWimmer** [comment]
This bug [has been fixed in gstreamer-plugins-base 1.0.9](http://lists.freedesktop.org/archives/gstreamer-devel/2013-August/042360.html).
However, [the latest version in Debian Sid is still 1.0.8](http://packages.debian.org/sid/gstreamer1.0-plugins-base).
Unless we want to compile gstreamer ourselves (which I would try to avoid), we need to wait a little longer.

**Comment by erlehmann** [comment]
Thanks, please close the bug as soon as gstreamer-plugins-base 1.0.9 is installed on the OAMI server.

**Comment by Daniel-Mietchen** [comment]
Another case: 10.1371/journal.pbio.1001886

```
Skipping download of <http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4061010/bin/pbio.1001886.s005.avi>.

Skipping download of <http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4061010/bin/pbio.1001886.s006.avi>.

Skipping <http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4061010/bin/pbio.1001886.s007.avi>, already exists at Wikimedia Commons.

Converting “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4061010%2Fbin%2Fpbio.1001886.s005.avi”, saving into “/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4061010%2Fbin%2Fpbio.1001886.s005.avi.ogg” … ERROR: Ihrer Installation von GStreamer fehlt ein Plugin.

ERROR:root:Unknown audio/video stream combination.: Skipping conversion of “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4061010%2Fbin%2Fpbio.1001886.s005.avi”.

Converting “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4061010%2Fbin%2Fpbio.1001886.s006.avi”, saving into “/home/danielmietchen/.cache/open-access-media-importer/media/refined/pmc_doi/http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4061010%2Fbin%2Fpbio.1001886.s006.avi.ogg” … ERROR: Ihrer Installation von GStreamer fehlt ein Plugin.

ERROR:root:Unknown audio/video stream combination.: Skipping conversion of “/home/danielmietchen/.cache/open-access-media-importer/media/raw/pmc_doi/http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4061010%2Fbin%2Fpbio.1001886.s006.avi”.
```

**Comment by Daniel-Mietchen** [comment]
Another one: 10.1371/journal.pone.0104250 .
